name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'

      - name: Install dependencies
        run: yarn install

      - name: Create .env file
        run: |
          echo "VITE_EMAIL=jiag293@gmail.com" >> .env
          echo "VITE_PHONE=0901410087" >> .env
          echo "VITE_ADDRESS=Lai Hung Cuong, Binh Chanh, Ho Chi Minh" >> .env
          echo "VITE_COUNTRY=Viet Nam" >> .env
          echo "VITE_DISCORD=https://discord.com/users/512904155065614336" >> .env
          echo "VITE_TELEGRAM=https://t.me/JiaG293" >> .env
          echo "VITE_FACEBOOK=" >> .env
          echo "VITE_GITHUB=https://github.com/JiaG293" >> .env
          echo "VITE_LINKEDIN=https://www.linkedin.com/in/jiag293" >> .env
          echo "VITE_CV=https://cv.jiag.id.vn/en" >> .env
          echo "VITE_SUB_CV=https://cv.jiag.id.vn/vi" >> .env
          echo "VITE_SERVICE_ID=" >> .env
          echo "VITE_TEMPLATE_ID=" >> .env
          echo "VITE_PUBLIC_KEY=" >> .env

      - name: Build project
        run: yarn build

      - name: Deploy to GitHub Pages
        run: yarn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
